FuCoreApp.Mvc/Models/ErrorViewModel.cs
namespace FuCoreApp.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FuCoreApp.Mvc/Controllers/CategoryApiController.cs
using AutoMapper;
using FuCoreApp.Mvc.ApiService;
using FuCoreApp.Mvc.DTOs;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FuCoreApp.Mvc.Controllers
{
    public class CategoryApiController : Controller
    {
        private readonly CategoryApiService _categoryApiService;
        private readonly IMapper _mapper;

        public CategoryApiController(CategoryApiService categoryApiService, IMapper mapper)
        {
            _categoryApiService = categoryApiService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var cat = _categoryApiService.GetAllAsync().Result;
            return View(_mapper.Map<IEnumerable<CategoryDto>>(cat));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public async  Task<IActionResult> Create(CategoryDto categoryDto)
        {
            if (ModelState.IsValid)
            {
                await _categoryApiService.AddAsync(categoryDto);
                return RedirectToAction("Index");
            }
            return View(categoryDto);
        }
   
        [HttpGet]

        public async Task<IActionResult> Update(int id)
        {
            var category = await _categoryApiService.GetByIdAsync(id);
            return View(_mapper.Map<CategoryDto>(category));
        }

        [HttpPost]
       public async Task<IActionResult> Update(CategoryDto categoryDto) 
        {
            await _categoryApiService.Update(categoryDto);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _categoryApiService.Remove(id);
            return RedirectToAction("Index");
        }
    }
}
// cat-dto-map

FuCoreApp.Mvc/Controllers/HomeController.cs
using FuCoreApp.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FuCoreApp.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FuCoreApp.Mvc/Controllers/ProductApiController.cs
using AutoMapper;
using FuCoreApp.Mvc.ApiService;
using FuCoreApp.Mvc.DTOs;
using Microsoft.AspNetCore.Mvc;

namespace FuCoreApp.Mvc.Controllers
{
    public class ProductApiController : Controller
    {
        private readonly ProductApiService _productApiService;
        private readonly IMapper _mapper;

        public ProductApiController(ProductApiService productApiService, IMapper mapper)
        {
            _productApiService = productApiService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var pro= _productApiService.GetAllAsync().Result;
            return View(_mapper.Map<IEnumerable<ProductDto>>(pro));
        }

        [HttpGet]

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Create(ProductDto productDto)
        {

            if (ModelState.IsValid)
            {
                await _productApiService.AddAsync(productDto);
                return RedirectToAction("Index");
            }
            return View(productDto);
        }
        /// <summary>
        /// ////////////////////
        /// </summary>
        /// <param ></param>
        /// <returns></returns>

        [HttpGet]

        public async Task<IActionResult> Update(int id)
        {
            var pro= await _productApiService.GetByIdAsync(id);
            return View(_mapper.Map<ProductDto>(pro));
        }

        [HttpPost]

        public async Task<IActionResult> Update(ProductDto productDto)
        {
            if (ModelState.IsValid)
            {
                await _productApiService.Update(productDto);
                return RedirectToAction("Index");
            }
            return View(productDto);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _productApiService.Remove(id);
            return RedirectToAction("Index");
        }

    }
}

FuCoreApp.Mvc/Views/CategoryApi/Create.cshtml
@model CategoryDto
@{
    ViewData["Title"] = "Create";
}

<h1>Api'den kategori ekleme</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-controller="CategoryApi" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name">Kategori ismi : </label>
                <input asp-for="Name"  class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group mt-3 float-end">
                <input type="submit" value="ekle" class="btn btn-primary mt-3" />
            </div>
        </form>
    </div>
</div>

FuCoreApp.Mvc/Views/CategoryApi/Index.cshtml
@model IEnumerable<CategoryDto>
@{
    ViewData["Title"] = "Index";
}

<h1>Api'den gelen Kategoriler Listesi</h1>

<a class="btn btn-primary mb-3" asp-action="Create">Kategori Ekle</a>

<table class="table table-bordered table-stripped">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Islemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ID</td>
                <td>@item.Name</td>
                <td>
                    <a class="btn btn-warning btn-sm" asp-action="Update" asp-route-Id="@item.ID">Guncelle</a>
                    <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-Id="@item.ID">Sil</a>
                </td>
            </tr>
        }

    </tbody>
</table>

FuCoreApp.Mvc/Views/CategoryApi/Update.cshtml
@model CategoryDto
@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name">Kategori ismi : </label>
                <input asp-for="Name"  class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group mt-3 float-end">
                <input type="submit" value="güncelle" class="btn btn-primary mt-3" />
            </div>
        </form>
    </div>
</div>

FuCoreApp.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FuCoreApp.Mvc/Views/ProductApi/Create.cshtml
@model ProductDto
@{
    ViewData["Title"] = "Create";
}

<h1>Yeni ürün ekleme</h1>



<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name">Ürün ismi : </label>
                <input asp-for="Name" class="form-control" />
                <label asp-for="Stock">Ürün stoğu : </label>
                <input asp-for="Stock" class="form-control" />
                <label asp-for="Price">Ürün ücret : </label>
                <input asp-for="Price" class="form-control" />
                <label asp-for="CategoryId"> kategori : </label>
                <input asp-for="CategoryId" class="form-control" />

                <span asp-validation-for="Name" class="text-danger"></span>
                <span asp-validation-for="Stock" class="text-danger"></span>
                <span asp-validation-for="Price" class="text-danger"></span>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group mt-3 float-end">
                <input type="submit" value="ekle" class="btn btn-primary mt-3" />
            </div>
        </form>
    </div>
</div>

FuCoreApp.Mvc/Views/ProductApi/Index.cshtml
@model IEnumerable<ProductDto>
@{
    ViewData["Title"] = "Index";
}

<h1>Api'den gelen ürünler listesi</h1>

<a class="btn btn-primary mb-3" asp-action="Create">Ürün Ekle</a>

<table class="table table-bordered table-stripped">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Stock</th>
            <th>Price</th>
            <th>Kategori ID</th>
            <th>Islemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ID</td>
                <td>@item.Name</td>
                <td>@item.Stock</td>
                <td>@item.Price</td>
                <td>@item.CategoryId</td>
                <td>
                    <a class="btn btn-warning btn-sm" asp-action="Update" asp-route-Id="@item.ID">Guncelle</a>
                   <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-Id="@item.ID" onclick="return confirm('Bu kaydi silmek istediginize eminmisiniz? Kayit kalici olarak silinecektir!!!')">Sil</a>

                </td>
            </tr>
        }

    </tbody>
</table>

FuCoreApp.Mvc/Views/ProductApi/Update.cshtml
@model ProductDto
@{
    ViewData["Title"] = "Update";
}

<h1>Güncelle Ürün</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name">Ürün ismi : </label>
                <input asp-for="Name" class="form-control" />
                <label asp-for="Stock">Ürün stoğu : </label>
                <input asp-for="Stock" class="form-control" />
                <label asp-for="Price">Ürün ücret : </label>
                <input asp-for="Price" class="form-control" />
                <label asp-for="CategoryId"> kategori : </label>
                <input asp-for="CategoryId" class="form-control" />

                <span asp-validation-for="Name" class="text-danger"></span>
                <span asp-validation-for="Stock" class="text-danger"></span>
                <span asp-validation-for="Price" class="text-danger"></span>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group mt-3 float-end">
                <input type="submit" value="güncelle" class="btn btn-primary mt-3" />
            </div>
        </form>
    </div>
</div>

FuCoreApp.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FuCoreApp.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FuCoreApp.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FuCoreApp.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CategoryApi" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductApi" asp-action="Index">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FuCoreApp.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>